name: helldivers2_companion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  cloud_firestore: ^6.0.1
  collection: ^1.19.1
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  forui: ^0.16.0
  forui_assets: ^0.16.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.2
  intl: ^0.20.2
  logging: ^1.3.0
  shared_preferences: ^2.5.3
  signals_flutter: ^6.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  firebase_core_platform_interface: ^6.0.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/news/
