name: helldivers2_companion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  cloud_firestore: ^6.0.1
  collection: ^1.19.1
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  forui: ^0.15.1
  forui_assets: ^0.15.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/news/
